var ScriptNames = {
    'HDFCBANK': { companyId: 9195, name:'hdfc-bank-ltd', mcName: 'HDFC Bank', lotSize: 1},
    'RELIANCE': { companyId: 13215, name:'reliance-industries-ltd', mcName: 'Reliance', lotSize: 1},
    'INFY': { companyId: 10960, name:'infosys-ltd', mcName: 'Infosys', lotSize: 300},
    'HDFC': { companyId: 13640, name:'housing-development-finance-corporation-ltd', mcName: 'HDFC', lotSize: 1},
    'ICICIBANK':{ companyId: 9194, name:'icici-bank-ltd', mcName: 'ICICI Bank', lotSize: 1},
    'TCS': { companyId: 8345, name:'tata-consultancy-services-ltd', mcName: 'TCS', lotSize: 150},
    'KOTAKBANK': { companyId: 12161, name:'kotak-mahindra-bank-ltd', mcName: 'Kotak Mahindra', lotSize: 1},
    'HINDUNILVR': { companyId: 13616, name:'hindustan-unilever-ltd', mcName: '', lotSize: 1},
    'ITC': { companyId: 13554, name:'itc-ltd', mcName: 'ITC', lotSize: 1},
    'AXISBANK':{ companyId: 9175, name:'axis-bank-ltd', mcName: 'Axis Bank', lotSize: 1},

// IT
'HCLTECH': { companyId: 4291, name:'hcl-technologies-ltd', mcName: 'HCL Tech', lotSize: 1},

//'JUSTDIAL': { companyId: 45529, name:'just-dial-ltd'},
'MINDTREE': { companyId: 15673, name:'mindtree-ltd', mcName: 'Mindtree', lotSize: 1},
//'NIITTECH': { companyId: 858, name:'niit-technologies-ltd'},

//'TATAELXSI': { companyId: 12207, name:'tata-elxsi-ltd'},
'TECHM': { companyId: 11221, name:'tech-mahindra-ltd', mcName: 'Tech Mahindra', lotSize: 1},
'WIPRO': { companyId: 12799, name:'wipro-ltd', mcName: 'Wipro', lotSize: 1},
// FINANCIAL SERVICES
//'BAJFINANCE': { companyId: 11260, name:'bajaj-finance-ltd'},
//'BAJAJFINSV': { companyId: 21426, name:'bajaj-finserv-ltd'},
//'BAJAJHLDNG': { companyId: 13977, name:'bajaj-holdings-investment-ltd'},
//'CHOLAFIN': { companyId: 12159, name:'cholamandalam-investment-finance-company-ltd'},
//'EDELWEISS': { companyId: 19100, name:'edelweiss-financial-services-ltd'},
'HDFCLIFE': { companyId: 3068, name:'hdfc-life-insurance-company-ltd', mcName: 'HDFC Life', lotSize: 1},

//'ICICIGI': { companyId: 1883, name:'icici-lombard-general-insurance-company-ltd'},
//'ICICIPRULI': { companyId: 1898, name:'icici-prudential-life-insurance-company-ltd'},
'IBULHSGFIN': { companyId: 15580, name:'indiabulls-housing-finance-ltd', mcName: 'Indiabulls Hsg', lotSize: 1},
//'M&MFIN': { companyId: 3540, name:'mahindra-mahindra-financial-services-ltd'},
'PFC': { companyId: 4519, name:'power-finance-corporation-ltd', mcName: 'Power Finance', lotSize: 1},
'RECLTD': { companyId: 4616, name:'rec-ltd', mcName: '', lotSize: 1},
'SBILIFE': { companyId: 2898, name:'sbi-life-insurance-company-ltd', mcName: 'SBI Life Insura', lotSize: 1},
'SRTRANSFIN': { companyId: 13106, name:'shriram-transport-finance-company-ltd', mcName: 'Shriram Trans', lotSize: 1},
// BANKS

//'BANKBARODA': { companyId: 12040, name:'bank-of-baroda'},
//'FEDERALBNK': { companyId: 9211, name:'federal-bank-ltd'},

//'IDFCFIRSTB': { companyId: 62245, name:'idfc-first-bank-ltd'},
//'INDUSINDBK': { companyId: 9196, name:'indusind-bank-ltd'},

'PNB':{ companyId: 11585, name:'punjab-national-bank', mcName: 'PNB', lotSize: 1},
'RBLBANK': { companyId: 7750, name:'rbl-bank-ltd', mcName: 'RBL Bank', lotSize: 1},
'SBIN':{ companyId: 11984, name:'state-bank-of-india', mcName: 'SBI', lotSize: 1},
//'YESBANK':{ companyId: 16552, name:'yes-bank-ltd'},

'BANDHANBNK': { companyId: 67665, name:'bandhan-bank-ltd', mcName: 'Bandhan Bank', lotSize: 1800},
// AUTOMOBILE
//'AMARAJABAT': { companyId: 12713, name:'amara-raja-batteries-ltd'},
'APOLLOTYRE': { companyId: 63, name:'apollo-tyres-ltd', mcName: 'Apollo Tyres', lotSize: 1},
//'ASHOKLEY': { companyId: 14041, name:'ashok-leyland-ltd'},
//'BAJAJ-AUTO': { companyId: 21430, name:'bajaj-auto-ltd'},
//'BHARATFORG': { companyId: 13958, name:'bharat-forge-ltd'},
//'BOSCHLTD': { companyId: 11911, name:'bosch-ltd'},
//'EICHERMOT': { companyId: 13787, name:'eicher-motors-ltd'},
//'EXIDEIND': { companyId: 13895, name:'exide-industries-ltd'},
'HEROMOTOCO': { companyId: 13636, name:'hero-motocorp-ltd', mcName: 'Hero Motocorp', lotSize: 1},
//'MRF': { companyId: 11381, name:'mrf-ltd'},
//'M&M': { companyId: 11898, name:'mahindra-mahindra-ltd'},
'MARUTI': { companyId: 11890, name:'maruti-suzuki-india-ltd', mcName: 'Maruti Suzuki', lotSize: 1},
//'MOTHERSUMI': { companyId: 10878, name:'motherson-sumi-systems-ltd'},
'TVSMOTOR': { companyId: 12940, name:'tvs-motor-company-ltd', mcName: 'TVS Motor', lotSize: 1},
'TATAMOTORS': { companyId: 12934, name:'tata-motors-ltd', mcName: 'Tata Motors', lotSize: 1},

// CONSUMER GOODS
'BRITANNIA': { companyId: 13934, name:'britannia-industries-ltd', mcName: 'Britannia', lotSize: 1},
//'COLPAL': { companyId: 13873, name:'colgate-palmolive-india-ltd'},
//'DABUR': { companyId: 11796, name:'dabur-india-ltd'},
//'EMAMILTD': { companyId: 5619, name:'emami-ltd'},
//'GODREJCP': { companyId: 1908, name:'godrej-consumer-products-ltd'},
//'GODREJIND': { companyId: 11764, name:'godrej-industries-ltd'},


//'JUBLFOOD': { companyId: 16224, name:'jubilant-foodworks-ltd'},
//'MARICO': { companyId: 5886, name:'marico-ltd'},
//'NESTLEIND': { companyId: 13330, name:'nestle-india-ltd'},
//'PGHH': { companyId: 13253, name:'procter-gamble-hygiene-healthcare-ltd'},
//'TATAGLOBAL': { companyId: 12929, name:'tata-global-beverages-ltd'},
'UBL': { companyId: 1367, name:'united-breweries-ltd', mcName: 'United Brewerie', lotSize: 1},
//'MCDOWELL-N': { companyId: 1714, name:'united-spirits-ltd'},

// MEDIA & ENTERTAINMENT
//'BALAJITELE': { companyId: 3376, name:'balaji-telefilms-ltd'},
//'DBCORP': { companyId: 30711, name:'db-corp-ltd'},
//'DISHTV': { companyId: 20201, name:'dish-tv-india-ltd'},
//'HATHWAY': { companyId: 30990, name:'hathway-cable-datacom-ltd'},
//'INOXLEISUR': { companyId: 1886, name:'inox-leisure-ltd'},
//'JAGRAN': { companyId: 17767, name:'jagran-prakashan-ltd'},
//'RADIOCITY': { companyId: 50029, name:'music-broadcast-ltd'},
//'NETWORK18': { companyId: 15747, name:'network-18-media-investments-ltd'},
//'PVR': { companyId: 16320, name:'pvr-ltd'},
//'SAREGAMA': { companyId: 13704, name:'saregama-india-ltd'},
//'SUNTV': { companyId: 17994, name:'sun-tv-network-ltd'},
//'TVTODAY': { companyId: 16508, name:'tv-today-network-ltd'},
//'TV18BRDCST': { companyId: 15481, name:'tv18-broadcast-ltd'},
//'ZEEL': { companyId: 11769, name:'zee-entertainment-enterprises-ltd'},
//'ZEEMEDIA': { companyId: 18879, name:'zee-media-corporation-ltd'},

// METALS
'APLAPOLLO': { companyId: 6683, name:'apl-apollo-tubes-ltd', mcName: 'Apollo Pipes', lotSize: 1},
'COALINDIA': { companyId: 11822, name:'coal-india-ltd', mcName: 'Coal India', lotSize: 1},
'HINDALCO': { companyId: 13637, name:'hindalco-industries-ltd', mcName: 'Hindalco', lotSize: 1},
'HINDCOPPER': { companyId: 11733, name:'hindustan-copper-ltd', mcName: '', lotSize: 1},
//'HINDZINC': { companyId: 11982, name:'hindustan-zinc-ltd'},
'JSWSTEEL': { companyId: 8352, name:'jsw-steel-ltd', mcName: 'JSW Steel', lotSize: 1},
'JINDALSTEL': { companyId: 4355, name:'jindal-steel-power-ltd', mcName: 'Jindal Steel', lotSize: 1},
//'MOIL': { companyId: 4501, name:'moil-ltd'},
'NMDC': { companyId: 11633, name:'nmdc-ltd', mcName: 'NMDC', lotSize: 1},
//'NATIONALUM': { companyId: 11997, name:'national-aluminium-company-ltd'},
//'RATNAMANI': { companyId: 10915, name:'ratnamani-metals-tubes-ltd'},
//'SAIL': { companyId: 11974, name:'steel-authority-of-india-sail-ltd'},
'TATASTEEL': { companyId: 12902, name:'tata-steel-ltd', mcName: 'Tata Steel', lotSize: 1},
//'VEDL': { companyId: 13111, name:'vedanta-ltd'},
//'WELCORP': { companyId: 5032, name:'welspun-corp-ltd'},

// PHARMA
'AUROPHARMA': { companyId: 8279, name:'aurobindo-pharma-ltd', mcName: 'Aurobindo Pharm', lotSize: 1},
'BIOCON': { companyId: 2082, name:'biocon-ltd', mcName: 'Biocon', lotSize: 1},
'CADILAHC': { companyId: 3778, name:'cadila-healthcare-ltd', mcName: 'Cadila Health', lotSize: 1},
'CIPLA': { companyId: 13917, name:'cipla-ltd', mcName: 'Cipla', lotSize: 1},
'DIVISLAB': { companyId: 3635, name:"divi's-laboratories-ltd", mcName: 'Divis Labs', lotSize: 1},
'DRREDDY': { companyId: 13841, name:"dr-reddy's-laboratories-ltd", mcName: 'Dr Reddys Labs', lotSize: 1},
'GLENMARK': { companyId: 4255, name:'glenmark-pharmaceuticals-ltd', mcName: 'Glenmark', lotSize: 1},
'LUPIN': { companyId: 10743, name:'lupin-ltd', mcName: 'Lupin', lotSize: 1},
//'PEL': { companyId: 13332, name:'piramal-enterprises-ltd'},
'SUNPHARMA': { companyId: 9134, name:'sun-pharmaceutical-industries-ltd', mcName: '', lotSize: 1},
'NATCOPHARM' : { companyId: 8305, name:'natco-pharma-ltd' , mcName: '', lotSize: 1},

// General
'VOLTAS': { companyId: 12815, name:'voltas-ltd', mcName: 'Voltas', lotSize: 1},
'BHARTIARTL': {companyId: 2718, name:'bharti-airtel-ltd', mcName: 'Bharti Airtel', lotSize: 1},
}